# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'started_window_vvpd.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication
from students_in_late_window import LateListWindow
from scoring_window import DeadlineScoresWindow

class StartedWindow(QWidget):
    def setupUi(self, startes_window):
        startes_window.setObjectName("startes_window")
        startes_window.resize(400, 300)
        startes_window.setStyleSheet("background-color: rgb(216, 229, 255);\n"
"font: 10pt \"Century Gothic\";\n"
"")
        self.choose_label = QtWidgets.QLabel(startes_window)
        self.choose_label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.choose_label.setStyleSheet("background-color: rgb(237, 242, 255);")
        self.choose_label.setObjectName("choose_label")
        self.deadline_score_button = QtWidgets.QPushButton(startes_window)
        self.deadline_score_button.setGeometry(QtCore.QRect(20, 70, 361, 51))
        self.deadline_score_button.setStyleSheet("QPushButton:hover {\n"
"    background-color:rgb(170, 183, 255); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.deadline_score_button.clicked.connect(self.show_scoring_window)

        self.deadline_score_button.setObjectName("deadline_score_button")
        self.view_late_students_button = QtWidgets.QPushButton(startes_window)
        self.view_late_students_button.setGeometry(QtCore.QRect(20, 180, 361, 51))
        self.view_late_students_button.setStyleSheet("QPushButton:hover {\n"
"    background-color:rgb(170, 183, 255); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.view_late_students_button.setObjectName("view_late_students_button")
        self.view_late_students_button.clicked.connect(self.show_students_in_late)

        self.retranslateUi(startes_window)
        QtCore.QMetaObject.connectSlotsByName(startes_window)
    def show_scoring_window(self):

        self.scoring_window=DeadlineScoresWindow()
        self.scoring_window.setupUi(self.scoring_window)
        self.scoring_window.show()


    def show_students_in_late(self):
        self.late_students = LateListWindow()
        self.late_students.setupUi(self.late_students)
        self.late_students.show()



    def retranslateUi(self, startes_window):
        _translate = QtCore.QCoreApplication.translate
        startes_window.setWindowTitle(_translate("startes_window", "Form"))
        self.choose_label.setText(_translate("startes_window", "Выберите, что вы хотите сделать"))
        self.deadline_score_button.setText(_translate("startes_window", "Рассчитать оценку в зависимости\n"
" от срока дедлайна"))
        self.view_late_students_button.setText(_translate("startes_window", "Узнать \"должников\""))


app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QWidget()
mainwindow = StartedWindow()
mainwindow.setupUi(window)


window.show()
sys.exit(app.exec_())