# -*- coding: utf-8 -*-
import re
import sys

# Form implementation generated from reading ui file 'students_in_late_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication
from practice4 import late_list

class LateListWindow(QWidget):
    def setupUi(self, late_list_window):
        late_list_window.setObjectName("late_list_window")
        late_list_window.resize(508, 403)
        late_list_window.setStyleSheet("background-color: rgb(216, 229, 255);\n"
"font: 10pt \"Century Gothic\";\n"
"")
        self.widget = QtWidgets.QWidget(late_list_window)
        self.widget.setGeometry(QtCore.QRect(10, 20, 491, 350))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.students_with_date_label = QtWidgets.QLabel(self.widget)
        self.students_with_date_label.setObjectName("students_with_date_label")
        self.verticalLayout.addWidget(self.students_with_date_label)
        self.students_with_date_plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.students_with_date_plainTextEdit.setStyleSheet("background-color: rgb(237, 242, 255);")
        self.students_with_date_plainTextEdit.setObjectName("students_with_date_plainTextEdit")
        self.verticalLayout.addWidget(self.students_with_date_plainTextEdit)
        self.deadline_date_label = QtWidgets.QLabel(self.widget)
        self.deadline_date_label.setObjectName("deadline_date_label")
        self.verticalLayout.addWidget(self.deadline_date_label)
        self.deadline_date_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.deadline_date_lineEdit.setStyleSheet("background-color: rgb(237, 242, 255);")
        self.deadline_date_lineEdit.setObjectName("deadline_date_lineEdit")
        self.verticalLayout.addWidget(self.deadline_date_lineEdit)
        self.show_students_in_late_pushButton = QtWidgets.QPushButton(self.widget)
        self.show_students_in_late_pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color:rgb(170, 183, 255); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.show_students_in_late_pushButton.setObjectName("show_students_in_late_pushButton")
        self.verticalLayout.addWidget(self.show_students_in_late_pushButton)
        self.show_results_students_label = QtWidgets.QLabel(self.widget)
        self.show_results_students_label.setStyleSheet("background-color: rgb(237, 242, 255);")
        self.show_results_students_label.setObjectName("show_results_students_label")
        self.verticalLayout.addWidget(self.show_results_students_label)
        self.students_with_date_plainTextEdit.setPlaceholderText('Вводите учеников в формате: Студент1: dd.mm.yyyy\nСтудент2: dd.mm.yyyy\nСтудент3: dd.mm.yyyy')
        self.retranslateUi(late_list_window)
        self.show_students_in_late_pushButton.clicked.connect(self.show_late_students)
        QtCore.QMetaObject.connectSlotsByName(late_list_window)
    def show_late_students(self):
        inp_students=self.students_with_date_plainTextEdit.toPlainText().split('\n')
        try:
            students={}
            for elem in inp_students:
                if elem.strip():
                    student, pass_date = elem.split(':')
                    students[student.strip()] = pass_date.strip()
            deadline_date=self.deadline_date_lineEdit.text()
            result=', '.join(late_list(students,deadline_date))
            if result==', '.join("тут нет должников ура"):
                self.show_results_students_label.setText("тут нет должников ура")
            else:

                self.show_results_students_label.setText(result)

        except ValueError:
            self.show_results_students_label.setText('Введенные вами данные\nнекорректны')

    def retranslateUi(self, late_list_window):
        _translate = QtCore.QCoreApplication.translate
        late_list_window.setWindowTitle(_translate("late_list_window", "Form"))
        self.students_with_date_label.setText(_translate("late_list_window", " Ученики(Ученик: дата сдачи)"))
        self.deadline_date_label.setText(_translate("late_list_window", " Дата дедлайна:"))
        self.show_students_in_late_pushButton.setText(_translate("late_list_window", "Показать должников"))
        self.show_results_students_label.setText(_translate("late_list_window", "Здесь будет показан результат"))  # Замените `your_module_name` на фактическое имя вашего модуля.

